version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  node:
    image: node:10-alpine
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
